[[redirects]]
  from='https://strong-buttercream-5b7d12.netlify.app/*'
  to='https://netlify-se-demo.com/:splat'
  status=301
  force=true

  [[redirects]]
  from='https://www.netlify-se-demo.com/*'
  to='https://netlify-se-demo.com/:splat'
  status=301
  force=true