[[redirects]]
  from='https://storied-dieffenbachia-a83060.netlify.app/'
  to='https://netlify-se-demo.com/'
  status=301
  force=true


[[redirects]]
  from='https://storied-dieffenbachia-a83060.netlify.app/*'
  to='https://netlify-se-demo.com/:splat'
  status=301
  force=true
